name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip openjdk-17-jdk \
          autoconf libtool pkg-config \
          zlib1g-dev libncurses5-dev \
          libncursesw5-dev libtinfo5 cmake \
          libffi-dev libssl-dev libltdl-dev \
          python3-pip
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools virtualenv
        pip install buildozer cython==0.29.36
    
    # Явная установка python-for-android
    - name: Clone python-for-android
      run: |
        git clone https://github.com/kivy/python-for-android.git
        cd python-for-android
        pip install .
    
    - name: Initialize Buildozer
      run: |
        buildozer init
        echo "p4a.branch = master" >> buildozer.spec
        echo "android.ndk_path = $HOME/.buildozer/android/platform/android-ndk-r25b" >> buildozer.spec
        
    - name: Fix permissions
      run: sudo chmod -R a+rwx .
      
    - name: Build APK
      run: |
        buildozer android clean
        buildozer -v android debug 2>&1 | tee build.log
        
    - name: Verify APK exists
      run: |
        if ls bin/*.apk 1> /dev/null 2>&1; then
          echo "APK found successfully"
        else
          echo "APK not found! Searching alternatives..."
          find . -name "*.apk" -print
          exit 1
        fi
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: fitness-tracker-apk
        path: bin/*.apk
        if-no-files-found: error
        
    - name: Upload build logs
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: build.log
