name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip openjdk-17-jdk \
          autoconf libtool pkg-config \
          zlib1g-dev libncurses5-dev \
          libncursesw5-dev libtinfo5 cmake \
          libffi-dev libssl-dev libltdl-dev
        
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip wheel setuptools virtualenv
        pip install buildozer cython==0.29.36
    
    - name: Fix permissions
      run: sudo chmod -R a+rwx .
      
    - name: Build APK
      run: |
        buildozer -v android debug 2>&1 | tee build.log
      
    - name: Upload APK artifacts
      uses: actions/upload-artifact@v4  # ИСПРАВЛЕННАЯ ВЕРСИЯ
      with:
        name: build-artifacts
        path: |
          bin/
          .buildozer/
          build.log
